# Generated by Django 4.0.3 on 2022-04-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
    ]
